export const api = {
  // user
  login: "/api/wechat/mini/login",
  register: "/user/register",
  logout: "/user/logout",
  home: "/api/store/index",
  newsInfo: "/api/master/newsInfo",
  newslist: "/api/master/newslist",
  news: "/api/master/news",
  myInfo: "/api/master/myinfo",
  userCenter: "/api/master/userCenter",
  mynotice: "/api/master/mynotice",
  noticeinfo: "/api/master/noticeinfo",
  noticedel: "/api/master/notice_del",
  orderlist: "/api/master/accept_order_list",
  userAgreement: "/api/master/user_agreement",
  orderInfo: "/api/master/orderInfo",
  feedbackType: "/api/user/feedbacktype",
  feedback: "/api/user/feedback",
  aboutUs: "/api/user/about_us",
  levelRule: "/api/master/level_rule",
  acceptOrder: "/api/master/accept_order",
  rejectReason: "/api/master/reject_reason",
  purse: "/api/master/my_purse",
  masterStatus: "/api/master/master_status",
  rejectOrder: "/api/master/reject_order",
  balance: "/api/master/balance",
  withdraw: "/api/master/withdraw",
  myorder: "/api/master/myorder",
  search: "/api/master/searchnews",
  finishservice: "/api/master/finishservice",

  //master
  master_application: "/api/user/master_application",
  application_edit: "/api/user/application_edit",
  application_status: "/api/user/application_status",
  contractinfo: "/api/user/contractinfo",
  sign_contract: "/api/user/sign_contract",

  // login: "/api/wechat/mini/login",
  decryptUserInfo: "/api/wechat/mini/decrypt-user-info",
  decryptMobile: "/api/wechat/mini/decrypt-mobile",
};
